name: R-CMD-check

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rcmdcheck
            any::testthat
            any::covr

      - name: Check
        uses: r-lib/actions/check-r-package@v2
