name: R-CMD-check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install devtools
        run: install.packages("devtools")
        shell: Rscript {0}

      - name: Install package dependencies
        run: devtools::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Run R CMD check
        run: devtools::check()
        shell: Rscript {0}
